### ISSUE TITLE
Badge component

### ISSUE THREAD

**Issue by jwerre** [surveyplanet/svelte_components#3]
- Could we potentially add icons to the badge via [slot](https://svelte.dev/docs#template-syntax-slot)?
- If no label is provided, it could just be a dot (see notification component #16 ) .

### Parameters

| Name  | Type   | Description               |
| ----- | ------ | ------------------------- |
| color | string | An alternate badge color. |

### Usage

```ts
<script>
	import {Badge} from '@surveyplanet/svelte-components';
</script>
<Badge color="rgba(225,0,0,.5)">Pro</Badge>

```

**Comment by serferdinand2** [comment]
Need to add tests
