### ISSUE TITLE
Dropdown component

### ISSUE THREAD

**Issue by jwerre** [surveyplanet/svelte_components#32]
![Image](https://user-images.githubusercontent.com/747587/212984706-4266244d-4bc5-466e-a60a-569ab9aa149d.png)

### Example

```html
<script>
	import { Dropdown } from '@surveyplanet/svelte_components';
	const changeEventHandler = (event) => {
		console.log(`You really like ${event.value}`);
	};
        data = [
		{
			label: 'Bengal tiger',
			id: 'bengal-tiger',
			meta: 'endangered',
		},
		{
			label: 'Siberian tiger',
			id: 'siberian-tiger',
			meta: 'endangered',
		},
		{
			label: 'Sumatran tiger',
			id: 'sumatran-tiger',
			meta: 'endangered',
		},
		{
			label: 'Caspian tiger',
			id: 'sumatran-tiger',
			meta: 'extinct',
		},
		{
			label: 'Indochinese tiger',
			id: 'indochinese-tiger',
			meta: 'endangered',
		},
		{
			label: 'Malayan tiger',
			id: 'malayan-tiger',
			meta: 'endangered',
		},
		{
			label: 'South China tiger',
			id: 'south-china-tiger',
			meta: 'endangered',
		},
	];
</script>

<Dropdown
        {data}
        value="bengal-tiger"
	label="Which is your favorite?"
	on:change="{changeEventHandler}"
	/>
```

### Properties

| Property           | Type    | Description                                                                             |
| ------------------ | ------- | --------------------------------------------------------------------------------------- |
| `value=null`       | String  | The initial value of the input.                                                         |
| `label=null`       | String  | The input label text. If no label text is give not label tag will be rendered.          |
| `data` | Object | The menu data. See menu component for details. |
| `searchable=false` | Boolean | Whether an input is searchable. When `true` a text input is bound the dropdown options. |
| `disabled=false`   | Boolean | Whether the input is disabled or not.                                                   |
| `readonly=false`   | Boolean | Whether the input is read only or not.                                                  |
| `required`         | String  | Whether a value is required or not.                                                                |

### Events

| Name     | Returns  | Description                                  |
| -------- | -------- | -------------------------------------------- |
| `focus`  | DOMEvent | Dispatched when the input is in focus.       |
| `blur`   | DOMEvent | Dispatched when the input loses focus.       |
| `change` | DOMEvent | Dispatched when the input value has changed. |

[MDN Docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select)
[Styles](https://dev.to/themodernweb/how-to-make-a-custom-select-input-fully-working-custom-options-input-3734)

**Comment by serferdinand2** [comment]
After the merge, the input field is not populating with the menu Lable. fix the bug

**Comment by serferdinand2** [comment]
Input label is populating but the search is no longer refreshing the menu.
