### ISSUE TITLE
Text input component

### ISSUE THREAD

**Issue by jwerre** [surveyplanet/svelte_components#33]
![Image](https://user-images.githubusercontent.com/747587/212984598-41d2c6f8-0e48-42da-be4b-056a4104047a.png)

### Example

```html
<script>
	import { Input } from '@surveyplanet/svelte_components';
	const keyupEventHandler = (event) => {
		console.log(event.key);
	};
</script>

<Input
	label="My Input"
	on:keyup="{keyupEventHandler}"
	/>
/></Input>
```

### Properties

| Property           | Type    | Description                                                                    |
| ------------------ | ------- | ------------------------------------------------------------------------------ |
| `value=null`       | String  | The initial value of the input.                                                |
| `label=null`       | String  | The input label text. If no label text is give not label tag will be rendered. |
| `placeholder=null` | String  | The input placeholder text.                                                    |
| `multiline=false`  | Boolean | Whether the input should accept multiple lines.                                |
| `disabled=false`   | Boolean | Whether the input is disabled or not.                                          |
| `readonly=false`   | Boolean | Whether the input is read only or not.                                         |
| `attr=null`        | Object  | Arbitrary attributes to be attached to the input.                              |
| `validate`         | String  | See validator utilities.                                                       |

### Events

| Name      | Returns  | Description                                  |
| --------- | -------- | -------------------------------------------- |
| `focus`   | DOMEvent | Dispatched when the input is in focus.       |
| `blur`    | DOMEvent | Dispatched when the input loses focus.       |
| `change`  | DOMEvent | Dispatched when the input value has changed. |
| `keydown` | KeyboardEvent | Dispatched when a key is fully depressed.    |
| `keyup`   | KeyboardEvent | Dispatched when a key is fully released.     |

**Comment by serferdinand2** [comment]
Pushed, 

Not working: 

-tests can't recognize event dispatched
-change event is not dispatched on multiline text input

**Comment by serferdinand2** [comment]
Check keyup, and keydown types for handlers for tests and make tests work 

Object.prototype.toString.call(event)
