### ISSUE TITLE
Avatar component

### ISSUE THREAD

**Issue by jwerre** [surveyplanet/svelte_components#6]
![Image](https://user-images.githubusercontent.com/747587/209881602-8c5b29a0-8364-4fdc-90af-9f6d59df2be9.png)

### Properties

| Property            | type   | description                                      |
| ------------------- | ------ | ------------------------------------------------ |
| `[diameter=36]`     | Number | The size of the circle either `36`, `48` or `62` |
| `[color="#9ee4fa"]` | String | The background color                             |
| `[email]` | String | Email address is used to figure out which avatar to use.                             |
| `[disabled]` | Boolean | If disabled click event won't dispatch and aria button label will not be applied.                             |

### Slots

| Name    | description                                 |
| ------- | ------------------------------------------- |
| `image` | Image could be a mascot or if profile image |

### Events

| Name          | description                        |
| ------------- | ---------------------------------- |
| `avatarClick` | Avatar component has been clicked. |

**Comment by serferdinand2** [comment]
Pushed documentation

**Comment by serferdinand2** [comment]
Make property disabled and change aria role when disabled

**Comment by serferdinand2** [comment]
Fixed aria-label and role
