### ISSUE TITLE
Menu component

### ISSUE THREAD

**Issue by jwerre** [surveyplanet/svelte_components#9]
![Image](https://user-images.githubusercontent.com/747587/209881790-889a36d5-98bb-4f8d-9397-bc1686af2762.png)
![Image](https://user-images.githubusercontent.com/747587/209881789-1733e65b-24ba-43c0-ade5-7fa28877fb9f.png)
![Image](https://user-images.githubusercontent.com/747587/209881788-e8559b5f-edea-44a8-8678-f04bf44f956b.png)
![Image](https://user-images.githubusercontent.com/747587/214102746-4ac5321b-d5be-413c-bc30-11efaa0db4f4.png)
![Image](https://user-images.githubusercontent.com/747587/214102745-1510c7b9-500d-4e1a-873f-d6825ff72fbe.png)

Menu should be able to detect its position inside the window and react accordingly. By default it should always open below and to the right of the button that triggered it. However, the but menu should never expand outside of the window. If it is to low it should expand up. If it is to far right it should expand left.

### Example

```html
<script>
	import { Menu, MenuItem } from '@surveyplanet/svelte_components';
	const changeEventHandler = (event) => {
		console.log(`You really like ${event.value}`);
	};
</script>

<Menu on:change="{changeHandler}">
	<MenuItem value="cucumber">Cucumber</MenuItem>
	<MenuItem value="cabbage">
		Cabbage
		<Menu>
			<MenuItem value="green cabbage">Green</MenuItem>
			<MenuItem value="red cabbage">Red</MenuItem>
			<MenuItem value="savoy cabbage">Savoy</MenuItem>
			<MenuItem value="napa cabbage">Napa</MenuItem>
		</Menu>
	</MenuItem>
	<MenuItem value="radish">Radish</MenuItem>
</Menu>
```

### Properties and Events

| Name   | Type                  | Description                                                                   |
| ------ | --------------------- | ----------------------------------------------------------------------------- |
| data   | `menuData[]`          | Menu data                                                                     |
| update | `CustomEvent<string>` | Dispatched when an item with submenu is clicked and it updates the menu state |
| click  | `CustomEvent<string>` | Dispatched when an item without submenu is clicked                            |

### Types

| Name     | Description                          |
| -------- | ------------------------------------ |
| menuData | Interface for menu item data         |
| IconName | Type for icon names used in the menu |

### menuData

| Property | Type       | Description                             |
| -------- | ---------- | --------------------------------------- |
| id       | string     | The id of the menu item                 |
| label    | string     | The text label of the menu item         |
| html     | string     | The html content of the menu item       |
| icon     | IconName   | The name of the icon used in the menu   |
| meta     | string     | The meta data associated with the item  |
| divide   | boolean    | If true, the item should have a divider |
| inline   | boolean    | If true, the item should be inline      |
| selected | boolean    | If true, the item is currently selected |
| submenu  | menuData[] | An array of submenu items               |

### CSS classes

| Class                       | Description                          |
| --------------------------- | ------------------------------------ |
| `.sp-menu`                  | The root menu element                |
| `.sp-menu--item`            | A menu item element                  |
| `.sp-menu--item--divide`    | A menu item with a divider element   |
| `.sp-menu--item--inline`    | A menu item with an inline element   |
| `.sp-menu--item--selected`  | A selected menu item                 |
| `.sp-menu--item--submenu`   | A menu item with a submenu           |
| `.sp-menu--back-btn`        | The back button element              |
| `.sp-menu--back-btn--label` | The label of the back button element |

### Relavent links:

-   [`<svelte:self>`](https://svelte.dev/docs#template-syntax-svelte-self)
-   [ recursive component with `self` ](https://svelte.dev/tutorial/svelte-self)
-   [`<svelte:fragment>`](https://svelte.dev/docs#template-syntax-svelte-fragment)
-   [`$$slots`](https://svelte.dev/docs#template-syntax-slot-$$slots)

**Comment by serferdinand2** [comment]
https://m3.material.io/components/menus/guidelines

**Comment by serferdinand2** [comment]
Add arrow up and down as well as right arrow handlers for navigating the menu

**Comment by serferdinand2** [comment]
Merged into the dropdown, when we finish dropdown, merge into main
